backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "/"
logo_url: "/assets/img/logo.svg"

collections:
  - label: "Şarkılar"
    name: "songs"
    file: "songs.json"
    format: "json"
    editor:
      preview: false
    fields:
      - label: "Şarkılar"
        name: "songs"
        widget: "list"
        collapsed: false
        allow_add: true
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Sanatçı", name: "artist", widget: "string", default: "Gökhan Özkanlı" }
          - { label: "Kapak", name: "cover", widget: "image" }
          - { label: "Ses Dosyası", name: "audio", widget: "file" }
          - { label: "Süre", name: "duration", widget: "string", required: false }

  - label: "Klipler"
    name: "videos"
    file: "videos.json"
    format: "json"
    editor:
      preview: false
    fields:
      - label: "Klipler"
        name: "videos"
        widget: "list"
        collapsed: false
        allow_add: true
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "Sanatçı", name: "artist", widget: "string", default: "Gökhan Özkanlı" }
          - { label: "Poster", name: "poster", widget: "image", required: false }
          - { label: "Video Dosyası", name: "video", widget: "file" }
          - { label: "Süre", name: "duration", widget: "string", required: false }
